name: IPAVIET
options:
  bundleIdPrefix: com.ipaviet
targets:
  IPAVIET:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [Sources]
    settings:
      GENERATE_INFOPLIST_FILE: "YES"
      INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
      CODE_SIGNING_REQUIRED: "NO"
      CODE_SIGNING_ALLOWED: "NO"
      CODE_SIGN_IDENTITY: ""
