name: Build IPAVIET Clean
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cai dat XcodeGen
        run: brew install xcodegen
      - name: Tao Cau Truc Xcode
        run: xcodegen generate
      - name: Dong Goi Khong Chung Chi
        run: |
          xcodebuild build -project IPAVIET.xcodeproj -scheme IPAVIET -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -derivedDataPath build_output
      - name: Tao File IPA
        run: |
          mkdir -p Payload
          cp -r build_output/Build/Products/Release-iphoneos/IPAVIET.app Payload/
          zip -r IPAVIET_Clean.ipa Payload
      - name: Xuat File
        uses: actions/upload-artifact@v4
        with:
          name: IPAVIET_Clean
          path: IPAVIET_Clean.ipa
